language: python
python:
  - "3.7"
dist: xenial
services:
  - postgresql
install: "pipenv install"
before_script:
  - psql -c 'create database comp3663;' -U postgres
  - cp .env.example .env
  - python manage.py migrate
script:
  - flake8
  - coverage run manage.py test --settings=djangoapp.tests_settings
after_success:
  - coveralls
