language: python
python:
  - "3.7.2"
install: "pipenv install"
before_script:
  - cp .env.example .env
  - python manage.py migrate
script:
  - flake8
  - coverage run manage.py test --settings=djangoapp.tests_settings
after_success:
  - coveralls
